export interface BibleBook {
  name: string;
  chapters: number;
}

export const bibleBooks: BibleBook[] = [
  { name: "Genesis", chapters: 50 },
  { name: "Exodus", chapters: 40 },
  { name: "Leviticus", chapters: 27 },
  { name: "Numbers", chapters: 36 },
  { name: "Deuteronomy", chapters: 34 },
  { name: "Joshua", chapters: 24 },
  { name: "Judges", chapters: 21 },
  { name: "Ruth", chapters: 4 },
  { name: "1 Samuel", chapters: 31 },
  { name: "2 Samuel", chapters: 24 },
  { name: "1 Kings", chapters: 22 },
  { name: "2 Kings", chapters: 25 },
  { name: "1 Chronicles", chapters: 29 },
  { name: "2 Chronicles", chapters: 36 },
  { name: "Ezra", chapters: 10 },
  { name: "Nehemiah", chapters: 13 },
  { name: "Esther", chapters: 10 },
  { name: "Job", chapters: 42 },
  { name: "Psalms", chapters: 150 },
  { name: "Proverbs", chapters: 31 },
  { name: "Ecclesiastes", chapters: 12 },
  { name: "Song of Solomon", chapters: 8 },
  { name: "Isaiah", chapters: 66 },
  { name: "Jeremiah", chapters: 52 },
  { name: "Lamentations", chapters: 5 },
  { name: "Ezekiel", chapters: 48 },
  { name: "Daniel", chapters: 12 },
  { name: "Hosea", chapters: 14 },
  { name: "Joel", chapters: 3 },
  { name: "Amos", chapters: 9 },
  { name: "Obadiah", chapters: 1 },
  { name: "Jonah", chapters: 4 },
  { name: "Micah", chapters: 7 },
  { name: "Nahum", chapters: 3 },
  { name: "Habakkuk", chapters: 3 },
  { name: "Zephaniah", chapters: 3 },
  { name: "Haggai", chapters: 2 },
  { name: "Zechariah", chapters: 14 },
  { name: "Malachi", chapters: 4 },
  { name: "Matthew", chapters: 28 },
  { name: "Mark", chapters: 16 },
  { name: "Luke", chapters: 24 },
  { name: "John", chapters: 21 },
  { name: "Acts", chapters: 28 },
  { name: "Romans", chapters: 16 },
  { name: "1 Corinthians", chapters: 16 },
  { name: "2 Corinthians", chapters: 13 },
  { name: "Galatians", chapters: 6 },
  { name: "Ephesians", chapters: 6 },
  { name: "Philippians", chapters: 4 },
  { name: "Colossians", chapters: 4 },
  { name: "1 Thessalonians", chapters: 5 },
  { name: "2 Thessalonians", chapters: 3 },
  { name: "1 Timothy", chapters: 6 },
  { name: "2 Timothy", chapters: 4 },
  { name: "Titus", chapters: 3 },
  { name: "Philemon", chapters: 1 },
  { name: "Hebrews", chapters: 13 },
  { name: "James", chapters: 5 },
  { name: "1 Peter", chapters: 5 },
  { name: "2 Peter", chapters: 3 },
  { name: "1 John", chapters: 5 },
  { name: "2 John", chapters: 1 },
  { name: "3 John", chapters: 1 },
  { name: "Jude", chapters: 1 },
  { name: "Revelation", chapters: 22 }
];

export interface ReadingPlanDay {
  day: number;
  title: string;
  reading: string;
  isCompleted?: boolean;
}

export const foundationsPlan: ReadingPlanDay[] = [
  { day: 1, title: "The Beginning", reading: "Genesis 1" },
  { day: 2, title: "God's Promise", reading: "Genesis 12" },
  { day: 3, title: "The Deliverer", reading: "Exodus 3" },
  { day: 4, title: "The Ten Commandments", reading: "Exodus 20" },
  { day: 5, title: "The New King", reading: "1 Samuel 16" },
  { day: 6, title: "A Shepherd's Song", reading: "Psalm 23" },
  { day: 7, title: "Repentance", reading: "Psalm 51" },
  { day: 8, title: "Wisdom", reading: "Proverbs 3" },
  { day: 9, title: "The Suffering Servant", reading: "Isaiah 53" },
  { day: 10, title: "A New Covenant", reading: "Jeremiah 31" },
  { day: 11, title: "The Birth of Christ", reading: "Luke 2" },
  { day: 12, title: "Sermon on the Mount", reading: "Matthew 5" },
  { day: 13, title: "The Good Samaritan", reading: "Luke 10" },
  { day: 14, title: "The Lost Son", reading: "Luke 15" },
  { day: 15, title: "The Bread of Life", reading: "John 6" },
  { day: 16, title: "The Resurrection", reading: "John 20" },
  { day: 17, title: "The Holy Spirit", reading: "Acts 2" },
  { day: 18, title: "Justified by Faith", reading: "Romans 5" },
  { day: 19, title: "More Than Conquerors", reading: "Romans 8" },
  { day: 20, title: "The Way of Love", reading: "1 Corinthians 13" },
  { day: 21, title: "New Creation", reading: "2 Corinthians 5" },
  { day: 22, title: "The Armor of God", reading: "Ephesians 6" },
  { day: 23, title: "The Mind of Christ", reading: "Philippians 2" },
  { day: 24, title: "Superiority of Christ", reading: "Hebrews 1" },
  { day: 25, title: "Faith and Works", reading: "James 2" },
  { day: 26, title: "Living Hope", reading: "1 Peter 1" },
  { day: 27, title: "God is Love", reading: "1 John 4" },
  { day: 28, title: "The Seven Churches", reading: "Revelation 2" },
  { day: 29, title: "The Throne Room", reading: "Revelation 4" },
  { day: 30, title: "New Heavens and Earth", reading: "Revelation 21" }
];
